// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thinktecture.Database;

#nullable disable

namespace Thinktecture.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20230103104258_TphEntities")]
    partial class TphEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Thinktecture:ComplexCollectionParameter:Thinktecture.Database.MyParameter", b =>
                {
                    b.Property<Guid>("Column1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Column2")
                        .HasColumnType("int");

                    b.ToTable("MyParameter", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Thinktecture:TempTable:Thinktecture.EntityFrameworkCore.TempTables.TempTable<Guid, Guid>", b =>
                {
                    b.Property<Guid>("Column1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Column2")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("#TempTable<Guid, Guid>", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Thinktecture:TempTable:Thinktecture.EntityFrameworkCore.TempTables.TempTable<Guid>", b =>
                {
                    b.Property<Guid>("Column1")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("#TempTable<Guid>", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Thinktecture.Database.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Thinktecture.Database.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Thinktecture.Database.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Thinktecture.Database.ParentTph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ParentProp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TPH", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("parent");
                });

            modelBuilder.Entity("Thinktecture.Database.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Thinktecture.Database.ChildTph", b =>
                {
                    b.HasBaseType("Thinktecture.Database.ParentTph");

                    b.Property<int>("ChildProp")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("child");
                });

            modelBuilder.Entity("Thinktecture.Database.GrandchildTph", b =>
                {
                    b.HasBaseType("Thinktecture.Database.ChildTph");

                    b.Property<int>("GrandChildProp")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("grandchild");
                });

            modelBuilder.Entity("Thinktecture.Database.Order", b =>
                {
                    b.HasOne("Thinktecture.Database.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Thinktecture.Database.OrderItem", b =>
                {
                    b.HasOne("Thinktecture.Database.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thinktecture.Database.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Thinktecture.Database.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Thinktecture.Database.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Thinktecture.Database.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
