// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thinktecture.TestDatabaseContext;

#nullable disable

namespace Thinktecture.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.InformationSchemaColumn", b =>
                {
                    b.Property<int?>("CHARACTER_MAXIMUM_LENGTH")
                        .HasColumnType("int");

                    b.Property<int?>("CHARACTER_OCTET_LENGTH")
                        .HasColumnType("int");

                    b.Property<string>("CHARACTER_SET_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHARACTER_SET_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHARACTER_SET_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLLATION_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLLATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLLATION_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLUMN_DEFAULT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLUMN_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DATA_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("DATETIME_PRECISION")
                        .HasColumnType("smallint");

                    b.Property<string>("DOMAIN_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOMAIN_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOMAIN_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IS_NULLABLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("NUMERIC_PRECISION")
                        .HasColumnType("tinyint");

                    b.Property<short?>("NUMERIC_PRECISION_RADIX")
                        .HasColumnType("smallint");

                    b.Property<int?>("NUMERIC_SCALE")
                        .HasColumnType("int");

                    b.Property<int>("ORDINAL_POSITION")
                        .HasColumnType("int");

                    b.Property<string>("TABLE_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("<<InformationSchemaColumn>>");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.InformationSchemaConstraintColumn", b =>
                {
                    b.Property<string>("COLUMN_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONSTRAINT_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONSTRAINT_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONSTRAINT_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("<<InformationSchemaConstraintColumn>>");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.InformationSchemaKeyColumn", b =>
                {
                    b.Property<string>("COLUMN_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONSTRAINT_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONSTRAINT_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONSTRAINT_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ORDINAL_POSITION")
                        .HasColumnType("int");

                    b.Property<string>("TABLE_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("<<InformationSchemaKeyColumn>>");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.InformationSchemaTableConstraint", b =>
                {
                    b.Property<string>("CONSTRAINT_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONSTRAINT_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONSTRAINT_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONSTRAINT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INITIALLY_DEFERRED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IS_DEFERRABLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_CATALOG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLE_SCHEMA")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("<<InformationSchemaTableConstraint>>");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ConvertibleClass")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PropertyWithBackingField")
                        .HasColumnType("int");

                    b.Property<string>("RequiredName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_privateField")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("TestEntities");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_Inline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_Inline");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_Inline_Inline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_Inline_Inline");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_Inline_SeparateMany", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_Inline_SeparateMany");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_Inline_SeparateOne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_Inline_SeparateOne");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateMany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_SeparateMany");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateMany_Inline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_SeparateMany_Inline");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateMany_SeparateMany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_SeparateMany_SeparateMany");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateMany_SeparateOne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_SeparateMany_SeparateOne");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateOne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_SeparateOne");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateOne_Inline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_SeparateOne_Inline");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateOne_SeparateMany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_SeparateOne_SeparateMany");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateOne_SeparateOne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TestEntities_Own_SeparateOne_SeparateOne");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityWithAutoIncrement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesWithAutoIncrement");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityWithDotnetDefaultValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("0b151271-79bb-4f6c-b85f-e8f61300ff1b"));

                    b.Property<int>("Int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("NullableInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("NullableString")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("4");

                    b.Property<string>("String")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("3");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesWithDotnetDefaultValues");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityWithRowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesWithRowVersion");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityWithShadowProperties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShadowIntProperty")
                        .HasColumnType("int");

                    b.Property<string>("ShadowStringProperty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesWithShadowProperties");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityWithSqlDefaultValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<int>("Int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("NullableInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("2");

                    b.Property<string>("NullableString")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'4'");

                    b.Property<string>("String")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'3'");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesWithDefaultValues");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestTemporalTableEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("Id");

                    b.ToTable("TestTemporalTableEntity", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestViewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("TestView");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity", b =>
                {
                    b.HasOne("Thinktecture.TestDatabaseContext.TestEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_Inline", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity", "InlineEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_InlineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_InlineId");

                            b1.ToTable("TestEntities_Own_Inline");

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_InlineId");
                        });

                    b.Navigation("InlineEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_Inline_Inline", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity_Owns_Inline", "InlineEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_Inline_InlineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_Inline_InlineId");

                            b1.ToTable("TestEntities_Own_Inline_Inline");

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_Inline_InlineId");

                            b1.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity", "InlineEntity", b2 =>
                                {
                                    b2.Property<Guid>("OwnedEntity_Owns_InlineTestEntity_Owns_Inline_InlineId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("IntColumn")
                                        .HasColumnType("int");

                                    b2.Property<string>("StringColumn")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnedEntity_Owns_InlineTestEntity_Owns_Inline_InlineId");

                                    b2.ToTable("TestEntities_Own_Inline_Inline");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedEntity_Owns_InlineTestEntity_Owns_Inline_InlineId");
                                });

                            b1.Navigation("InlineEntity")
                                .IsRequired();
                        });

                    b.Navigation("InlineEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_Inline_SeparateMany", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity_Owns_SeparateMany", "InlineEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_Inline_SeparateManyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_Inline_SeparateManyId");

                            b1.ToTable("TestEntities_Own_Inline_SeparateMany");

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_Inline_SeparateManyId");

                            b1.OwnsMany("Thinktecture.TestDatabaseContext.OwnedEntity", "SeparateEntities", b2 =>
                                {
                                    b2.Property<Guid>("OwnedEntity_Owns_SeparateManyTestEntity_Owns_Inline_SeparateManyId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"), 1L, 1);

                                    b2.Property<int>("IntColumn")
                                        .HasColumnType("int");

                                    b2.Property<string>("StringColumn")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnedEntity_Owns_SeparateManyTestEntity_Owns_Inline_SeparateManyId", "Id");

                                    b2.ToTable("InlineEntities_SeparateMany", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedEntity_Owns_SeparateManyTestEntity_Owns_Inline_SeparateManyId");
                                });

                            b1.Navigation("SeparateEntities");
                        });

                    b.Navigation("InlineEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_Inline_SeparateOne", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity_Owns_SeparateOne", "InlineEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_Inline_SeparateOneId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_Inline_SeparateOneId");

                            b1.ToTable("TestEntities_Own_Inline_SeparateOne");

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_Inline_SeparateOneId");

                            b1.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity", "SeparateEntity", b2 =>
                                {
                                    b2.Property<Guid>("OwnedEntity_Owns_SeparateOneTestEntity_Owns_Inline_SeparateOneId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("IntColumn")
                                        .HasColumnType("int");

                                    b2.Property<string>("StringColumn")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnedEntity_Owns_SeparateOneTestEntity_Owns_Inline_SeparateOneId");

                                    b2.ToTable("InlineEntities_SeparateOne", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedEntity_Owns_SeparateOneTestEntity_Owns_Inline_SeparateOneId");
                                });

                            b1.Navigation("SeparateEntity")
                                .IsRequired();
                        });

                    b.Navigation("InlineEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateMany", b =>
                {
                    b.OwnsMany("Thinktecture.TestDatabaseContext.OwnedEntity", "SeparateEntities", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_SeparateManyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_SeparateManyId", "Id");

                            b1.ToTable("SeparateEntitiesMany", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_SeparateManyId");
                        });

                    b.Navigation("SeparateEntities");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateMany_Inline", b =>
                {
                    b.OwnsMany("Thinktecture.TestDatabaseContext.OwnedEntity_Owns_Inline", "SeparateEntities", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_SeparateMany_InlineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_SeparateMany_InlineId", "Id");

                            b1.ToTable("SeparateEntitiesMany_Inline", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_SeparateMany_InlineId");

                            b1.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity", "InlineEntity", b2 =>
                                {
                                    b2.Property<Guid>("OwnedEntity_Owns_InlineTestEntity_Owns_SeparateMany_InlineId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("OwnedEntity_Owns_InlineId")
                                        .HasColumnType("int");

                                    b2.Property<int>("IntColumn")
                                        .HasColumnType("int");

                                    b2.Property<string>("StringColumn")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnedEntity_Owns_InlineTestEntity_Owns_SeparateMany_InlineId", "OwnedEntity_Owns_InlineId");

                                    b2.ToTable("SeparateEntitiesMany_Inline");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedEntity_Owns_InlineTestEntity_Owns_SeparateMany_InlineId", "OwnedEntity_Owns_InlineId");
                                });

                            b1.Navigation("InlineEntity")
                                .IsRequired();
                        });

                    b.Navigation("SeparateEntities");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateMany_SeparateMany", b =>
                {
                    b.OwnsMany("Thinktecture.TestDatabaseContext.OwnedEntity_Owns_SeparateMany", "SeparateEntities", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_SeparateMany_SeparateManyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_SeparateMany_SeparateManyId", "Id");

                            b1.ToTable("SeparateEntitiesMany_SeparateEntitiesMany", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_SeparateMany_SeparateManyId");

                            b1.OwnsMany("Thinktecture.TestDatabaseContext.OwnedEntity", "SeparateEntities", b2 =>
                                {
                                    b2.Property<Guid>("OwnedEntity_Owns_SeparateManyTestEntity_Owns_SeparateMany_SeparateManyId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("OwnedEntity_Owns_SeparateManyId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"), 1L, 1);

                                    b2.Property<int>("IntColumn")
                                        .HasColumnType("int");

                                    b2.Property<string>("StringColumn")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnedEntity_Owns_SeparateManyTestEntity_Owns_SeparateMany_SeparateManyId", "OwnedEntity_Owns_SeparateManyId", "Id");

                                    b2.ToTable("SeparateEntitiesMany_SeparateEntitiesMany_Inner", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedEntity_Owns_SeparateManyTestEntity_Owns_SeparateMany_SeparateManyId", "OwnedEntity_Owns_SeparateManyId");
                                });

                            b1.Navigation("SeparateEntities");
                        });

                    b.Navigation("SeparateEntities");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateMany_SeparateOne", b =>
                {
                    b.OwnsMany("Thinktecture.TestDatabaseContext.OwnedEntity_Owns_SeparateOne", "SeparateEntities", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_SeparateMany_SeparateOneId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_SeparateMany_SeparateOneId", "Id");

                            b1.ToTable("SeparateEntitiesMany_SeparateEntitiesOne", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_SeparateMany_SeparateOneId");

                            b1.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity", "SeparateEntity", b2 =>
                                {
                                    b2.Property<Guid>("OwnedEntity_Owns_SeparateOneTestEntity_Owns_SeparateMany_SeparateOneId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("OwnedEntity_Owns_SeparateOneId")
                                        .HasColumnType("int");

                                    b2.Property<int>("IntColumn")
                                        .HasColumnType("int");

                                    b2.Property<string>("StringColumn")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnedEntity_Owns_SeparateOneTestEntity_Owns_SeparateMany_SeparateOneId", "OwnedEntity_Owns_SeparateOneId");

                                    b2.ToTable("SeparateEntitiesMany_SeparateEntitiesOne_Inner", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedEntity_Owns_SeparateOneTestEntity_Owns_SeparateMany_SeparateOneId", "OwnedEntity_Owns_SeparateOneId");
                                });

                            b1.Navigation("SeparateEntity")
                                .IsRequired();
                        });

                    b.Navigation("SeparateEntities");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateOne", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity", "SeparateEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_SeparateOneId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_SeparateOneId");

                            b1.ToTable("SeparateEntitiesOne", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_SeparateOneId");
                        });

                    b.Navigation("SeparateEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateOne_Inline", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity_Owns_Inline", "SeparateEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_SeparateOne_InlineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_SeparateOne_InlineId");

                            b1.ToTable("SeparateEntitiesOne_Inline", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_SeparateOne_InlineId");

                            b1.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity", "InlineEntity", b2 =>
                                {
                                    b2.Property<Guid>("OwnedEntity_Owns_InlineTestEntity_Owns_SeparateOne_InlineId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("IntColumn")
                                        .HasColumnType("int");

                                    b2.Property<string>("StringColumn")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnedEntity_Owns_InlineTestEntity_Owns_SeparateOne_InlineId");

                                    b2.ToTable("SeparateEntitiesOne_Inline");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedEntity_Owns_InlineTestEntity_Owns_SeparateOne_InlineId");
                                });

                            b1.Navigation("InlineEntity")
                                .IsRequired();
                        });

                    b.Navigation("SeparateEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateOne_SeparateMany", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity_Owns_SeparateMany", "SeparateEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_SeparateOne_SeparateManyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_SeparateOne_SeparateManyId");

                            b1.ToTable("SeparateEntitiesOne_SeparateMany", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_SeparateOne_SeparateManyId");

                            b1.OwnsMany("Thinktecture.TestDatabaseContext.OwnedEntity", "SeparateEntities", b2 =>
                                {
                                    b2.Property<Guid>("OwnedEntity_Owns_SeparateManyTestEntity_Owns_SeparateOne_SeparateManyId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"), 1L, 1);

                                    b2.Property<int>("IntColumn")
                                        .HasColumnType("int");

                                    b2.Property<string>("StringColumn")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnedEntity_Owns_SeparateManyTestEntity_Owns_SeparateOne_SeparateManyId", "Id");

                                    b2.ToTable("SeparateEntitiesOne_SeparateMany_Inner", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedEntity_Owns_SeparateManyTestEntity_Owns_SeparateOne_SeparateManyId");
                                });

                            b1.Navigation("SeparateEntities");
                        });

                    b.Navigation("SeparateEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity_Owns_SeparateOne_SeparateOne", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity_Owns_SeparateOne", "SeparateEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntity_Owns_SeparateOne_SeparateOneId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("int");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TestEntity_Owns_SeparateOne_SeparateOneId");

                            b1.ToTable("SeparateEntitiesOne_SeparateOne", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestEntity_Owns_SeparateOne_SeparateOneId");

                            b1.OwnsOne("Thinktecture.TestDatabaseContext.OwnedEntity", "SeparateEntity", b2 =>
                                {
                                    b2.Property<Guid>("OwnedEntity_Owns_SeparateOneTestEntity_Owns_SeparateOne_SeparateOneId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("IntColumn")
                                        .HasColumnType("int");

                                    b2.Property<string>("StringColumn")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnedEntity_Owns_SeparateOneTestEntity_Owns_SeparateOne_SeparateOneId");

                                    b2.ToTable("SeparateEntitiesOne_SeparateOne_Inner", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedEntity_Owns_SeparateOneTestEntity_Owns_SeparateOne_SeparateOneId");
                                });

                            b1.Navigation("SeparateEntity")
                                .IsRequired();
                        });

                    b.Navigation("SeparateEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
