// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thinktecture.TestDatabaseContext;

namespace Thinktecture.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20210226205403_Add_tables_with_owned_entities")]
    partial class Add_tables_with_owned_entities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.SqliteIndex", b =>
                {
                    b.Property<byte[]>("Name")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Origin")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Partial")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Seq")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Unique")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.ToView("pragma temp.index_list('<<table-name>>')");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.SqliteMaster", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Rootpage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sql")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tbl_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.ToView("sqlite_temp_master");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.SqliteTableInfo", b =>
                {
                    b.Property<long>("CId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Dflt_Value")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NotNull")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PK")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.ToView("PRAGMA_TABLE_INFO('<<table-name>>')");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConvertibleClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyWithBackingField")
                        .HasColumnType("INTEGER");

                    b.Property<int>("_privateField")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("TestEntities");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityOwningInlineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesOwningInlineEntity");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityOwningManyEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesOwningManyEntities");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityOwningOneSeparateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesOwningOneSeparateEntity");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityWithAutoIncrement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesWithAutoIncrement");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityWithDotnetDefaultValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new Guid("0b151271-79bb-4f6c-b85f-e8f61300ff1b"));

                    b.Property<int>("Int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int?>("NullableInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<string>("NullableString")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("4");

                    b.Property<string>("String")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("3");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesWithDotnetDefaultValues");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityWithShadowProperties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShadowIntProperty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShadowStringProperty")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesWithShadowProperties");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityWithSqlDefaultValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("NullableInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("2");

                    b.Property<string>("NullableString")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'4'");

                    b.Property<string>("String")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'3'");

                    b.HasKey("Id");

                    b.ToTable("TestEntitiesWithDefaultValues");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity", b =>
                {
                    b.HasOne("Thinktecture.TestDatabaseContext.TestEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityOwningInlineEntity", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedInlineEntity", "InlineEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntityOwningInlineEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("TEXT");

                            b1.HasKey("TestEntityOwningInlineEntityId");

                            b1.ToTable("TestEntitiesOwningInlineEntity");

                            b1.WithOwner()
                                .HasForeignKey("TestEntityOwningInlineEntityId");
                        });

                    b.Navigation("InlineEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityOwningManyEntities", b =>
                {
                    b.OwnsMany("Thinktecture.TestDatabaseContext.OwnedSeparateEntity", "SeparateEntities", b1 =>
                        {
                            b1.Property<Guid>("TestEntityOwningManyEntitiesId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("TEXT");

                            b1.HasKey("TestEntityOwningManyEntitiesId", "Id");

                            b1.ToTable("SeparateEntities_Many");

                            b1.WithOwner()
                                .HasForeignKey("TestEntityOwningManyEntitiesId");
                        });

                    b.Navigation("SeparateEntities");
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntityOwningOneSeparateEntity", b =>
                {
                    b.OwnsOne("Thinktecture.TestDatabaseContext.OwnedSeparateEntity", "SeparateEntity", b1 =>
                        {
                            b1.Property<Guid>("TestEntityOwningOneSeparateEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("IntColumn")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StringColumn")
                                .HasColumnType("TEXT");

                            b1.HasKey("TestEntityOwningOneSeparateEntityId");

                            b1.ToTable("SeparateEntities_One");

                            b1.WithOwner()
                                .HasForeignKey("TestEntityOwningOneSeparateEntityId");
                        });

                    b.Navigation("SeparateEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Thinktecture.TestDatabaseContext.TestEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
